### ISSUE TITLE
Ad blocker not working

### ISSUE THREAD

**Issue by RevealedSoulEven** [pantsufan/Magisk-Ad-Blocking-Module#20]
I installed the module in magisk but the ad blocker isn't working. So I replaced the hosts file with the one on github (updated yesterday) but still no ads are being blocked anywhere, neither website ads nor in any app.

**Comment by chaoscreater** [comment]
Same. Running latest Magisk and it's not blocking ads. Private DNS blocks ads just fine, but this module doesn't seem to do anything....

**Comment by chaoscreater** [comment]
OP created a Magisk module to block ads, but it doesn't work. Then he goes and close the issue because it's "not planned". The sole purpose of the tool is to block ads and it doesn't do what it's supposed to and the issue is somehow ignored. Huh..?

Anyway, anyone reading this comment should just use the LSPosed module AdClose, it works really well and you can target specific apps to block ads, instead of system-wide. Or just use Adblock or Private DNS (NextDNS.io is free).
