### ISSUE TITLE
Hosts file unchanged since 26th July.

### ISSUE THREAD

**Issue by macerg** [pantsufan/Magisk-Ad-Blocking-Module#24]
As it says in description. 
Normally changes daily.  Have there really been no changes since 26th July?

**Comment by kusti420** [comment]
what change were u expecting?

**Comment by macerg** [comment]
The normal daily update where new addresses are added. No changes since last Wednesday.

**Comment by macerg** [comment]
.....also, the number of blocked domains seems to have reduced radically. Has the list been rationalised?

**Comment by macerg** [comment]
Still no change since 26th July. Strange,  used to change every day. Iirc, used to be 10's of thousands domain names. Now only 7k ish.

**Comment by pantsufan** [comment]
The host file underwent a modification due to numerous complaints about sluggish performance on various devices. This prompted me to streamline the host entries, optimizing them specifically for use on Android devices. Regarding host file entries that remained unaffected, I was unable to automate the procedure due to time constraints. Currently, the script can only be executed from my virtual machine, necessitating manual uploading to GitHub. I trust this addresses all of your inquiries.

**Comment by macerg** [comment]
Ok, that explains it all! Thanks for the update.
